ci:
    autofix_prs: true
    autoupdate_schedule: "quarterly"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, dev, --branch, main]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  # this hook is broken since I introduced a CHANGELOG.md, see
  # https://github.com/Lucas-C/pre-commit-hooks-nodejs/issues/8
  #- repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  #  rev: v1.1.1
  #  hooks:
  #    - id: markdown-toc

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [
          --in-place,
          --remove-unused-variables,
          --ignore-init-module-imports,
          --remove-all-unused-imports,
        ]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
        - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
