site_name: idefix_cli
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

markdown_extensions:
- admonition
#  - pymdownx.details
#  - pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

plugins:
- include-markdown
- mkdocstrings:
    custom_templates: templates
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
          heading_level: 0
