name: CD
on:
  push:
    tags: v*
jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/idefix-cli
    permissions:
      id-token: write
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install build dependencies
      run: python -m pip install build wheel
    - name: Build distributions
      shell: bash -l {0}
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
